### ISSUE TITLE
build fails on alpine linux

### ISSUE THREAD

**Issue by cdaringe** [osquery/osquery#4694]
### What version of `osquery` are you using? What operating system. Be specific.

- version: latest at time of writing, dbac4ea
- alpine version: 3.8

### What have you already tried?

- https://github.com/facebook/osquery/blob/master/docs/wiki/development/building.md#building-on-linuxhttps://github.com/facebook/osquery/blob/master/docs/wiki/development/building.md#building-on-linux

in a Dockerfile,
```Dockerfile
FROM alpine:3.8
RUN apk update
# RUN apk add python python-dev
RUN apk add sudo \
  make \
  python \
  ruby \
  git \
  bash
RUN mkdir /osquery-build
WORKDIR /osquery-build
RUN git clone https://github.com/facebook/osquery
WORKDIR /osquery-build/osquery
RUN ls -al
RUN make deps
RUN make
```

### What did you expect to see?

not an error

### What did you see instead?

```
Step 10/17 : RUN make deps
 ---> Running in 5294f6e41048
Traceback (most recent call last):
  File "./tools/get_platform.py", line 224, in <module>
    familyAction()
  File "./tools/get_platform.py", line 196, in familyAction
    family, osType = _platform()
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "./tools/get_platform.py", line 216, in <module>
    platformAction()
  File "./tools/get_platform.py", line 188, in platformAction
    family, osType = _platform()
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "./tools/get_platform.py", line 220, in <module>
    distroAction()
  File "./tools/get_platform.py", line 192, in distroAction
    family, osType = _platform()
TypeError: 'NoneType' object is not iterable
./tools/lib.sh: line 29: =: command not found
```

**Comment by fser** [comment]
In order to get linuxbrew working on alpine, you also have to get through https://github.com/Linuxbrew/brew/wiki/Alpine-Linux

**Comment by Smjert** [comment]
This refers to the old build system and Alpine is not supported.

**Comment by smarttang** [comment]
In new version, osquery can't use in Alpine?
