### ISSUE TITLE
oss-fuzz report for fuzz-config: rapidjson::GenericValue::GetStringLength() 

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#5920]
Here's a trace from oss-fuzz. This still reproduces with the master branch of RapidJSON. It may not be an issue with RapidJSON itself, but our usage.

## ASAN crash output

```
--
  | WARNING: Logging before InitGoogleLogging() is written to STDERR
  | I1022 14:11:03.299330     1 rocksdb.cpp:148] Rocksdb open failed (5:0) IO error: While mkdir if missing: /var/osquery/osquery.db: No such file or directory
  | I1022 14:11:03.299407     1 rocksdb.cpp:156] Opening RocksDB failed: Continuing with read-only support
  | INFO: Seed: 1591393716
  | INFO: Loaded 1 modules   (483617 inline 8-bit counters): 483617 [0x494b1f0, 0x49c1311),
  | INFO: Loaded 1 PC tables (483617 PCs): 483617 [0x49c1318,0x5122528),
  | /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_osquery_cdc768d81d4ebf2d756b2790a06516e02cdefe91/revisions/osqueryfuzz-config: Running 1 inputs 100 time(s) each.
  | Running: /crash-b70a25ba35c7ad69da85fab6efceae953d7b5c5e
  | AddressSanitizer:DEADLYSIGNAL
  | =================================================================
  | ==1==ERROR: AddressSanitizer: SEGV on unknown address 0x01807fff8001 (pc 0x0000015507cf bp 0x7fff2494e2b0 sp 0x7fff2494e270 T0)
  | ==1==The signal is caused by a READ memory access.
  | #0 0x15507ce in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::GetStringLength() const osquery/libraries/cmake/source/rapidjson/src/include/rapidjson/document.h:1808:87
  | #1 0x15507ce in bool rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::StringEqual<rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&) const osquery/libraries/cmake/source/rapidjson/src/include/rapidjson/document.h:2126
  | #2 0x1550696 in rapidjson::GenericMemberIterator<false, rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::FindMember<rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&) osquery/libraries/cmake/source/rapidjson/src/include/rapidjson/document.h:1289:22
  | #3 0x15504dd in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::FindMember(char const*) osquery/libraries/cmake/source/rapidjson/src/include/rapidjson/document.h:1265:16
  | #4 0x1550303 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::FindMember(char const*) const osquery/libraries/cmake/source/rapidjson/src/include/rapidjson/document.h:1268:100
  | #5 0x151a004 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::HasMember(char const*) const osquery/libraries/cmake/source/rapidjson/src/include/rapidjson/document.h:1225:51
  | #6 0x15971c2 in osquery::Pack::initialize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&) osquery/osquery/config/packs.cpp:121:11
  | #7 0x1526a5e in osquery::Pack::Pack(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&) osquery/osquery/include/osquery/packs.h:44:5
  | #8 0x152682b in std::__1::__unique_if<osquery::Pack>::__unique_single std::__1::make_unique<osquery::Pack, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&&&) /usr/local/osquery-toolchain/usr/include/c++/v1/memory:3132:32
  | #9 0x151195c in osquery::Config::addPack(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&)::$_2::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&) const osquery/osquery/config/config.cpp:345:22
  | #10 0x1511507 in osquery::Config::addPack(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&) osquery/osquery/config/config.cpp:359:7
  | #11 0x151960f in osquery::Config::updateSource(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) osquery/osquery/config/config.cpp:655:11
  | #12 0x1515cdb in osquery::Config::update(std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > const&) osquery/osquery/config/config.cpp:767:19
  | #13 0x18ee8f9 in LLVMFuzzerTestOneInput osquery/osquery/main/harnesses/fuzz_config.cpp:34:26
  | #14 0x13d81ea in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /opt/toolchain/llvm/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:533:15
  | #15 0x13cb791 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /opt/toolchain/llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:280:6
  | #16 0x13d05fb in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /opt/toolchain/llvm/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:709:9
  | #17 0x13f78a2 in main /opt/toolchain/llvm/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
  | #18 0x7fe718cc782f in __libc_start_main /build/glibc-LK5gWL/glibc-2.23/csu/libc-start.c:291
```

## Input test case
```
{"packs":{"*":{"":" "}}}
```

**Comment by packetzero** [comment]
Looks like we don't check that the pack value is an object.

```
    for (const auto& pack : obj.GetObject()) {
      addSinglePack(pack.name.GetString(), pack.value);
    }
```
should probably be something like
```
    for (const auto& pack : obj.GetObject()) {
      if (!pack.value.isObject()) {
         // stop fuzzing me, Teddy! 😁
         LOG(WARN) << "parse error : pack should be object";
         break;
      }
      addSinglePack(pack.name.GetString(), pack.value);
    }
```
