### ISSUE TITLE
Fix Python test_5_daemon_sigint

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#6300]
```
88: test_5_daemon_sigint (__main__.DaemonTests) ...   File "test_osqueryd.py", line 148, in test_5_daemon_sigint
88:     self.assertTrue(daemon.retcode in [0])
88: 
88:   File "test_osqueryd.py", line 148, in test_5_daemon_sigint
88:     self.assertTrue(daemon.retcode in [0])
88: 
88:   File "test_osqueryd.py", line 148, in test_5_daemon_sigint
88:     self.assertTrue(daemon.retcode in [0])
88: 
88: Test (attempt 1) DaemonTests::test_5_daemon_sigint failed: False is not true
88: Test (attempt 2) DaemonTests::test_5_daemon_sigint failed: False is not true
88: Test (attempt 3) DaemonTests::test_5_daemon_sigint failed: False is not true
88: FAIL

88: FAIL: test_5_daemon_sigint (__main__.DaemonTests)
88: ----------------------------------------------------------------------
88: Traceback (most recent call last):
88:   File "/__w/1/b/usr/src/debug/osquery/build/tools/tests/test_base.py", line 546, in wrapper
88:     raise exceptions[0]
88:   File "/__w/1/b/usr/src/debug/osquery/build/tools/tests/test_base.py", line 527, in attempt
88:     worked = gen(this)
88:   File "test_osqueryd.py", line 148, in test_5_daemon_sigint
88:     self.assertTrue(daemon.retcode in [0])
88: AssertionError: False is not true
```

This supposedly means osquery is actually returning with an error, so that error should be checked too.
Also `self.assertTrue(daemon.retcode in [0])` should really be `self.assertEqual(daemon.retcode, 0)`.

**Comment by Smjert** [comment]
I haven't seen this in quite a while, I'll close it for now.
