### ISSUE TITLE
Fix python test tools_tests_testosqueryi failing with a pexpect timeout

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#6667]
```
2020-09-22T00:29:40.9877270Z       Start 82: tools_tests_testosqueryi
2020-09-22T00:29:40.9878880Z 
2020-09-22T00:29:40.9885320Z 82: Test command: /usr/local/Cellar/cmake/3.18.2/bin/cmake "-E" "env" "PYTHONPATH=/Users/runner/work/1/b/build/python_path" "/usr/local/Frameworks/Python.framework/Versions/3.8/bin/python3.8" "-u" "test_osqueryi.py" "--verbose" "--build" "/Users/runner/work/1/b/build" "--test-configs-dir" "/Users/runner/work/1/b/build/test_configs"
2020-09-22T00:29:40.9888730Z 82: Test timeout computed to be: 300
2020-09-22T00:29:42.5733030Z 82: test_atc (__main__.OsqueryiTest) ... ok
2020-09-22T00:29:43.8485230Z 82: test_config_bad_json (__main__.OsqueryiTest) ... ok
2020-09-22T00:29:44.1036210Z 82: test_config_check_example (__main__.OsqueryiTest)
2020-09-22T00:29:44.7182350Z 82: Test that the example config passes ... b''
2020-09-22T00:29:44.7193710Z 82: b'I0922 00:29:44.402832 389166528 init.cpp:338] osquery initialized [version=4.5.0-11-gd75e6cda]\nI0922 00:29:44.403643 389166528 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: \nI0922 00:29:44.403935 389166528 init.cpp:549] An error occured during extension manager startup: Extensions disabled\nI0922 00:29:44.404043 389166528 auto_constructed_tables.cpp:97] Removing stale ATC entries\nI0922 00:29:44.506242 389166528 dispatcher.cpp:149] Thread: 0x1173235c0 requesting a stop\nI0922 00:29:44.506319 389166528 dispatcher.cpp:122] Thread: 0x1173235c0 requesting a join\nI0922 00:29:44.506341 389166528 dispatcher.cpp:144] Services and threads have been cleared\n'
2020-09-22T00:29:44.7201740Z 82: ok
2020-09-22T00:29:45.5129270Z 82: test_config_check_failure_invalid_path (__main__.OsqueryiTest) ... b''
2020-09-22T00:29:45.5140440Z 82: b'I0922 00:29:45.229584 454784448 init.cpp:338] osquery initialized [version=4.5.0-11-gd75e6cda]\nI0922 00:29:45.230721 454784448 rocksdb.cpp:132] Opening RocksDB handle: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.db7470\nI0922 00:29:45.287302 454784448 init.cpp:549] An error occured during extension manager startup: Extensions disabled\nI0922 00:29:45.287561 454784448 auto_constructed_tables.cpp:97] Removing stale ATC entries\nError reading config: config file does not exist: /this/path/does/not/exist\nI0922 00:29:45.288429 454784448 dispatcher.cpp:149] Thread: 0x11b1b75c0 requesting a stop\nI0922 00:29:45.288496 454784448 dispatcher.cpp:122] Thread: 0x11b1b75c0 requesting a join\nI0922 00:29:45.288516 454784448 dispatcher.cpp:144] Services and threads have been cleared\n'
2020-09-22T00:29:45.5147700Z 82: ok
2020-09-22T00:29:46.4469110Z 82: test_config_check_failure_missing_plugin (__main__.OsqueryiTest) ... ok
2020-09-22T00:29:47.3100840Z 82: test_config_check_failure_valid_path (__main__.OsqueryiTest) ... ok
2020-09-22T00:29:47.6556240Z 82: test_config_check_success (__main__.OsqueryiTest)
2020-09-22T00:29:48.4299670Z 82: Test that a 0-config passes ... b''
2020-09-22T00:29:48.4313430Z 82: b'I0922 00:29:47.967650 175244736 init.cpp:338] osquery initialized [version=4.5.0-11-gd75e6cda]\nI0922 00:29:47.968536 175244736 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: \nI0922 00:29:47.968920 175244736 rocksdb.cpp:132] Opening RocksDB handle: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.db7897\nI0922 00:29:48.021553 175244736 init.cpp:549] An error occured during extension manager startup: Extensions disabled\nI0922 00:29:48.021697 175244736 auto_constructed_tables.cpp:97] Removing stale ATC entries\nI0922 00:29:48.115816 175244736 auto_constructed_tables.cpp:228] ATC table: test_atc Registered\nI0922 00:29:48.117702 175244736 dispatcher.cpp:149] Thread: 0x10a7205c0 requesting a stop\nI0922 00:29:48.117779 175244736 dispatcher.cpp:122] Thread: 0x10a7205c0 requesting a join\nI0922 00:29:48.117801 175244736 dispatcher.cpp:144] Services and threads have been cleared\n'
2020-09-22T00:29:48.4322220Z 82: ok
2020-09-22T00:29:48.6911070Z 82: test_config_dump (__main__.OsqueryiTest)
2020-09-22T00:29:49.2529430Z 82: Test that config raw output is dumped when requested ... b'I0922 00:29:48.986953 143881664 init.cpp:338] osquery initialized [version=4.5.0-11-gd75e6cda]\nI0922 00:29:48.987821 143881664 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: \nI0922 00:29:48.988159 143881664 init.cpp:549] An error occured during extension manager startup: Extensions disabled\nI0922 00:29:48.988267 143881664 auto_constructed_tables.cpp:97] Removing stale ATC entries\nI0922 00:29:48.989483 143881664 config.cpp:504] Requesting shutdown after dumping config\nI0922 00:29:48.989881 143881664 dispatcher.cpp:149] Thread: 0x1089375c0 requesting a stop\nI0922 00:29:48.989984 143881664 dispatcher.cpp:122] Thread: 0x1089375c0 requesting a join\nI0922 00:29:48.990006 143881664 dispatcher.cpp:144] Services and threads have been cleared\n'
2020-09-22T00:29:49.2538050Z 82: ok
2020-09-22T00:29:49.5249260Z 82: test_error (__main__.OsqueryiTest)
2020-09-22T00:29:50.1917400Z 82: Test that we throw an error on bad query ... ok
2020-09-22T00:29:52.1302470Z 82: test_foreign_tables (__main__.OsqueryiTest) ... ok
2020-09-22T00:29:52.3710400Z 82: test_json_output (__main__.OsqueryiTest)
2020-09-22T00:29:52.9607430Z 82: Test that the output of --json is valid json ... b'[\n  {"0":"0"}\n]\n'
2020-09-22T00:29:52.9610530Z 82: b''
2020-09-22T00:29:52.9612000Z 82: ok
2020-09-22T00:29:53.2545740Z 82: test_meta_commands (__main__.OsqueryiTest)
2020-09-22T00:30:27.9979270Z 82: Test the supported meta shell/help/info commands ... ERROR
2020-09-22T00:30:58.0067830Z 82: test_time (__main__.OsqueryiTest) ... ERROR
2020-09-22T00:31:28.0160910Z 82: test_time_using_all (__main__.OsqueryiTest) ... ERROR
2020-09-22T00:31:28.0165310Z 82: 
2020-09-22T00:31:28.0168590Z 82: ======================================================================
2020-09-22T00:31:28.0172090Z 82: ERROR: test_meta_commands (__main__.OsqueryiTest)
2020-09-22T00:31:28.0175370Z 82: Test the supported meta shell/help/info commands
2020-09-22T00:31:28.0180620Z 82: ----------------------------------------------------------------------
2020-09-22T00:31:28.0183610Z 82: Traceback (most recent call last):
2020-09-22T00:31:28.0187040Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 1535, in expect_loop
2020-09-22T00:31:28.0189190Z 82:     c = self.read_nonblocking(self.maxread, timeout)
2020-09-22T00:31:28.0192570Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 968, in read_nonblocking
2020-09-22T00:31:28.0195610Z 82:     raise TIMEOUT('Timeout exceeded.')
2020-09-22T00:31:28.0196860Z 82: pexpect.TIMEOUT: Timeout exceeded.
2020-09-22T00:31:28.0197810Z 82: 
2020-09-22T00:31:28.0199280Z 82: During handling of the above exception, another exception occurred:
2020-09-22T00:31:28.0200470Z 82: 
2020-09-22T00:31:28.0201390Z 82: Traceback (most recent call last):
2020-09-22T00:31:28.0203320Z 82:   File "test_osqueryi.py", line 185, in test_meta_commands
2020-09-22T00:31:28.0204950Z 82:     result = self.osqueryi.run_command(command)
2020-09-22T00:31:28.0206670Z 82:   File "/Users/runner/work/1/b/build/tools/tests/test_base.py", line 69, in patched_run_command
2020-09-22T00:31:28.0208230Z 82:     if self._expect_prompt(timeout=timeout) == 1:
2020-09-22T00:31:28.0211230Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/replwrap.py", line 61, in _expect_prompt
2020-09-22T00:31:28.0213240Z 82:     return self.child.expect_exact([self.prompt, self.continuation_prompt],
2020-09-22T00:31:28.0216230Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 1498, in expect_exact
2020-09-22T00:31:28.0218030Z 82:     return self.expect_loop(searcher_string(pattern_list),
2020-09-22T00:31:28.0221050Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 1568, in expect_loop
2020-09-22T00:31:28.0223940Z 82:     raise TIMEOUT(str(err) + '\n' + str(self))
2020-09-22T00:31:28.0225410Z 82: pexpect.TIMEOUT: Timeout exceeded.
2020-09-22T00:31:28.0226600Z 82: <pexpect.spawn object at 0x10b23dc40>
2020-09-22T00:31:28.0227860Z 82: version: 3.3
2020-09-22T00:31:28.0229050Z 82: command: /Users/runner/work/1/b/build/osquery/osqueryi
2020-09-22T00:31:28.0236780Z 82: args: ['/Users/runner/work/1/b/build/osquery/osqueryi', '--flagfile=/dev/null', '--database_path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.db8942', '--pidfile=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.pid', '--config_path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.conf', '--extensions_autoload=/dev/null', '--extensions_socket=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.em', '--extensions_interval=1', '--extensions_timeout=0', '--watchdog_level=3', '--disable_logging=true', '--disable_events=true', '--force=true']
2020-09-22T00:31:51.2475630Z 82: searcher: <pexpect.searcher_string object at 0x10b23dc70>
2020-09-22T00:31:51.2479730Z 82: buffer (last 100 chars): b'alue: ""\r\n       output: stdout\r\n    separator: ","\r\n        width: \r\n\r\nNon-default flags/options:\r\n'
2020-09-22T00:31:51.2483720Z 82: before (last 100 chars): b'alue: ""\r\n       output: stdout\r\n    separator: ","\r\n        width: \r\n\r\nNon-default flags/options:\r\n'
2020-09-22T00:31:51.2486630Z 82: after: <class 'pexpect.TIMEOUT'>
2020-09-22T00:31:51.2487720Z 82: match: None
2020-09-22T00:31:51.2489740Z 82: match_index: None
2020-09-22T00:31:51.2490610Z 82: exitstatus: None
2020-09-22T00:31:51.2491470Z 82: flag_eof: False
2020-09-22T00:31:51.2492260Z 82: pid: 47097
2020-09-22T00:31:51.2610500Z 82: child_fd: 4
2020-09-22T00:31:51.2612170Z 82: closed: False
2020-09-22T00:31:51.2613820Z 82: timeout: 30
2020-09-22T00:31:51.2617950Z 82: delimiter: <class 'pexpect.EOF'>
2020-09-22T00:31:51.2619930Z 82: logfile: None
2020-09-22T00:31:51.2621760Z 82: logfile_read: None
2020-09-22T00:31:51.2623520Z 82: logfile_send: None
2020-09-22T00:31:51.2625430Z 82: maxread: 2000
2020-09-22T00:31:51.2627100Z 82: ignorecase: False
2020-09-22T00:31:51.2628780Z 82: searchwindowsize: None
2020-09-22T00:31:51.2630670Z 82: delaybeforesend: 0.05
2020-09-22T00:31:51.2632410Z 82: delayafterclose: 0.1
2020-09-22T00:31:51.2634430Z 82: delayafterterminate: 0.1
2020-09-22T00:31:51.2635990Z 82: 
2020-09-22T00:31:51.2638010Z 82: ======================================================================
2020-09-22T00:31:51.2640920Z 82: ERROR: test_time (__main__.OsqueryiTest)
2020-09-22T00:31:51.2645460Z 82: ----------------------------------------------------------------------
2020-09-22T00:31:51.2649720Z 82: Traceback (most recent call last):
2020-09-22T00:31:51.2668200Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 1535, in expect_loop
2020-09-22T00:31:51.2670820Z 82:     c = self.read_nonblocking(self.maxread, timeout)
2020-09-22T00:31:51.2675310Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 968, in read_nonblocking
2020-09-22T00:31:51.2679320Z 82:     raise TIMEOUT('Timeout exceeded.')
2020-09-22T00:31:51.2681360Z 82: pexpect.TIMEOUT: Timeout exceeded.
2020-09-22T00:31:51.2683080Z 82: 
2020-09-22T00:31:51.2685060Z 82: During handling of the above exception, another exception occurred:
2020-09-22T00:31:51.2687150Z 82: 
2020-09-22T00:31:51.2688850Z 82: Traceback (most recent call last):
2020-09-22T00:31:51.2690780Z 82:   File "test_osqueryi.py", line 30, in setUp
2020-09-22T00:31:51.2693120Z 82:     self.osqueryi = test_base.OsqueryWrapper(command=self.binary)
2020-09-22T00:31:51.2696150Z 82:   File "/Users/runner/work/1/b/build/tools/tests/test_base.py", line 191, in __init__
2020-09-22T00:31:51.2704080Z 82:     super().__init__(
2020-09-22T00:31:51.2733130Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/replwrap.py", line 54, in __init__
2020-09-22T00:31:51.2735400Z 82:     self._expect_prompt()
2020-09-22T00:31:51.2738690Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/replwrap.py", line 61, in _expect_prompt
2020-09-22T00:31:51.2741940Z 82:     return self.child.expect_exact([self.prompt, self.continuation_prompt],
2020-09-22T00:31:51.2745490Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 1498, in expect_exact
2020-09-22T00:31:51.2747810Z 82:     return self.expect_loop(searcher_string(pattern_list),
2020-09-22T00:31:51.2751130Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 1568, in expect_loop
2020-09-22T00:31:51.2754990Z 82:     raise TIMEOUT(str(err) + '\n' + str(self))
2020-09-22T00:31:51.2756990Z 82: pexpect.TIMEOUT: Timeout exceeded.
2020-09-22T00:31:51.2758690Z 82: <pexpect.spawn object at 0x10b23db80>
2020-09-22T00:31:51.2761290Z 82: version: 3.3
2020-09-22T00:31:51.2763900Z 82: command: /Users/runner/work/1/b/build/osquery/osqueryi
2020-09-22T00:31:51.2812700Z 82: args: ['/Users/runner/work/1/b/build/osquery/osqueryi', '--flagfile=/dev/null', '--database_path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.db3209', '--pidfile=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.pid', '--config_path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.conf', '--extensions_autoload=/dev/null', '--extensions_socket=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.em', '--extensions_interval=1', '--extensions_timeout=0', '--watchdog_level=3', '--disable_logging=true', '--disable_events=true', '--force=true']
2020-09-22T00:31:51.2819670Z 82: searcher: <pexpect.searcher_string object at 0x10b25a730>
2020-09-22T00:31:51.2822850Z 82: buffer (last 100 chars): b''
2020-09-22T00:31:51.2826030Z 82: before (last 100 chars): b''
2020-09-22T00:31:51.2828960Z 82: after: <class 'pexpect.TIMEOUT'>
2020-09-22T00:31:51.2830730Z 82: match: None
2020-09-22T00:31:51.2832270Z 82: match_index: None
2020-09-22T00:31:51.2833790Z 82: exitstatus: None
2020-09-22T00:31:51.2835510Z 82: flag_eof: False
2020-09-22T00:31:51.2839360Z 82: pid: 47099
2020-09-22T00:31:51.2840940Z 82: child_fd: 5
2020-09-22T00:31:51.2842300Z 82: closed: False
2020-09-22T00:31:51.2843610Z 82: timeout: 30
2020-09-22T00:31:51.2847230Z 82: delimiter: <class 'pexpect.EOF'>
2020-09-22T00:31:51.2848900Z 82: logfile: None
2020-09-22T00:31:51.2850310Z 82: logfile_read: None
2020-09-22T00:31:51.2851690Z 82: logfile_send: None
2020-09-22T00:31:51.2853120Z 82: maxread: 2000
2020-09-22T00:31:51.2854480Z 82: ignorecase: False
2020-09-22T00:31:51.2856010Z 82: searchwindowsize: None
2020-09-22T00:31:51.2857540Z 82: delaybeforesend: 0.05
2020-09-22T00:31:51.2858980Z 82: delayafterclose: 0.1
2020-09-22T00:31:51.2860510Z 82: delayafterterminate: 0.1
2020-09-22T00:31:51.2861900Z 82: 
2020-09-22T00:31:51.2863540Z 82: ======================================================================
2020-09-22T00:31:51.2865640Z 82: ERROR: test_time_using_all (__main__.OsqueryiTest)
2020-09-22T00:31:51.2869540Z 82: ----------------------------------------------------------------------
2020-09-22T00:31:51.2871730Z 82: Traceback (most recent call last):
2020-09-22T00:31:51.2876290Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 1535, in expect_loop
2020-09-22T00:31:51.2878780Z 82:     c = self.read_nonblocking(self.maxread, timeout)
2020-09-22T00:31:51.2883040Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 968, in read_nonblocking
2020-09-22T00:31:51.2887060Z 82:     raise TIMEOUT('Timeout exceeded.')
2020-09-22T00:31:51.2888950Z 82: pexpect.TIMEOUT: Timeout exceeded.
2020-09-22T00:31:51.2890420Z 82: 
2020-09-22T00:31:51.2892170Z 82: During handling of the above exception, another exception occurred:
2020-09-22T00:31:51.2893960Z 82: 
2020-09-22T00:31:51.2895730Z 82: Traceback (most recent call last):
2020-09-22T00:31:51.2897530Z 82:   File "test_osqueryi.py", line 30, in setUp
2020-09-22T00:31:51.2899490Z 82:     self.osqueryi = test_base.OsqueryWrapper(command=self.binary)
2020-09-22T00:31:51.2901770Z 82:   File "/Users/runner/work/1/b/build/tools/tests/test_base.py", line 191, in __init__
2020-09-22T00:31:51.2903730Z 82:     super().__init__(
2020-09-22T00:31:51.2907660Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/replwrap.py", line 54, in __init__
2020-09-22T00:31:51.2909850Z 82:     self._expect_prompt()
2020-09-22T00:31:51.2914110Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/replwrap.py", line 61, in _expect_prompt
2020-09-22T00:31:51.2916950Z 82:     return self.child.expect_exact([self.prompt, self.continuation_prompt],
2020-09-22T00:31:51.2921500Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 1498, in expect_exact
2020-09-22T00:31:51.2924190Z 82:     return self.expect_loop(searcher_string(pattern_list),
2020-09-22T00:31:51.2930050Z 82:   File "/usr/local/lib/python3.8/site-packages/pexpect/__init__.py", line 1568, in expect_loop
2020-09-22T00:31:51.2934240Z 82:     raise TIMEOUT(str(err) + '\n' + str(self))
2020-09-22T00:31:51.2936360Z 82: pexpect.TIMEOUT: Timeout exceeded.
2020-09-22T00:31:51.2938220Z 82: <pexpect.spawn object at 0x10b25a4c0>
2020-09-22T00:31:51.2940780Z 82: version: 3.3
2020-09-22T00:31:51.2942630Z 82: command: /Users/runner/work/1/b/build/osquery/osqueryi
2020-09-22T00:31:51.2954260Z 82: args: ['/Users/runner/work/1/b/build/osquery/osqueryi', '--flagfile=/dev/null', '--database_path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.db5034', '--pidfile=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.pid', '--config_path=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.conf', '--extensions_autoload=/dev/null', '--extensions_socket=/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/osquery-tests-python-501/tests.em', '--extensions_interval=1', '--extensions_timeout=0', '--watchdog_level=3', '--disable_logging=true', '--disable_events=true', '--force=true']
2020-09-22T00:31:51.2963010Z 82: searcher: <pexpect.searcher_string object at 0x10b25a490>
2020-09-22T00:31:51.2966800Z 82: buffer (last 100 chars): b''
2020-09-22T00:31:51.2970420Z 82: before (last 100 chars): b''
2020-09-22T00:31:51.2974010Z 82: after: <class 'pexpect.TIMEOUT'>
2020-09-22T00:31:51.2975780Z 82: match: None
2020-09-22T00:31:51.2977350Z 82: match_index: None
2020-09-22T00:31:51.2978880Z 82: exitstatus: None
2020-09-22T00:31:51.2980460Z 82: flag_eof: False
2020-09-22T00:31:51.2981940Z 82: pid: 47100
2020-09-22T00:31:51.2983350Z 82: child_fd: 6
2020-09-22T00:31:51.2985040Z 82: closed: False
2020-09-22T00:31:51.2986580Z 82: timeout: 30
2020-09-22T00:31:51.2989920Z 82: delimiter: <class 'pexpect.EOF'>
2020-09-22T00:31:51.2991780Z 82: logfile: None
2020-09-22T00:31:51.2993310Z 82: logfile_read: None
2020-09-22T00:31:51.2995170Z 82: logfile_send: None
2020-09-22T00:31:51.2996760Z 82: maxread: 2000
2020-09-22T00:31:51.2998320Z 82: ignorecase: False
2020-09-22T00:31:51.2999880Z 82: searchwindowsize: None
2020-09-22T00:31:51.3001570Z 82: delaybeforesend: 0.05
2020-09-22T00:31:51.3003210Z 82: delayafterclose: 0.1
2020-09-22T00:31:51.3004860Z 82: delayafterterminate: 0.1
2020-09-22T00:31:51.3006340Z 82: 
2020-09-22T00:31:51.3009930Z 82: ----------------------------------------------------------------------
2020-09-22T00:31:51.3012150Z 82: Ran 14 tests in 106.562s
2020-09-22T00:31:51.3013700Z 82: 
2020-09-22T00:31:51.3015050Z 82: FAILED (errors=3)
2020-09-22T00:31:51.3017390Z 82/83 Test #82: tools_tests_testosqueryi ..............................................***Failed  108.96 sec
```

**Comment by mike-myers-tob** [comment]
Fixed by @theopolis in #6688
