### ISSUE TITLE
Fix tools_tests_testosqueryi, test_config_check_failure_missing_plugin test case

### ISSUE THREAD

**Issue by Smjert** [osquery/osquery#6668]
```
2020-09-22T00:05:33.2130509Z       Start 77: tools_tests_testosqueryi
2020-09-22T00:05:33.2131301Z 
2020-09-22T00:05:33.2132462Z 77: Test command: "C:\Program Files\CMake\bin\cmake.exe" "-E" "env" "PYTHONPATH=D:/a/1/b/build/python_path" "C:/hostedtoolcache/windows/Python/3.8.5/x64/python.exe" "-u" "test_osqueryi.py" "--verbose" "--build" "D:/a/1/b/build" "--test-configs-dir" "D:/a/1/b/build/test_configs"
2020-09-22T00:05:33.2134221Z 77: Test timeout computed to be: 300
2020-09-22T00:05:34.4425423Z 77: test_atc (__main__.OsqueryiTest) ... ok
2020-09-22T00:05:35.4706676Z 77: test_config_bad_json (__main__.OsqueryiTest) ... ok
2020-09-22T00:05:35.4707964Z 77: test_config_check_example (__main__.OsqueryiTest)
2020-09-22T00:05:36.7882197Z 77: Test that the example config passes ... b''
2020-09-22T00:05:36.7885328Z 77: b'I0922 00:05:35.505930  1596 init.cpp:338] osquery initialized [version=4.5.0-11-gd75e6cda]\r\nI0922 00:05:35.506938  1596 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: \r\nI0922 00:05:35.506938  1596 init.cpp:549] An error occured during extension manager startup: Extensions disabled\r\nI0922 00:05:35.506938  1596 auto_constructed_tables.cpp:97] Removing stale ATC entries\r\nI0922 00:05:36.577956  1596 dispatcher.cpp:149] Thread: 1596 requesting a stop\r\nI0922 00:05:36.577956  1596 dispatcher.cpp:122] Thread: 1596 requesting a join\r\nI0922 00:05:36.577956  1596 dispatcher.cpp:144] Services and threads have been cleared\r\n'
2020-09-22T00:05:36.7888113Z 77: ok
2020-09-22T00:05:37.2791569Z 77: test_config_check_failure_invalid_path (__main__.OsqueryiTest) ... b''
2020-09-22T00:05:37.2794669Z 77: b'I0922 00:05:36.823863  6372 init.cpp:338] osquery initialized [version=4.5.0-11-gd75e6cda]\r\nI0922 00:05:36.824864  6372 rocksdb.cpp:132] Opening RocksDB handle: C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\osquery-tests-python-VssAdministrator\\tests.db2010\r\nI0922 00:05:37.068222  6372 init.cpp:549] An error occured during extension manager startup: Extensions disabled\r\nI0922 00:05:37.068222  6372 auto_constructed_tables.cpp:97] Removing stale ATC entries\r\nError reading config: config file does not exist: /this/path/does/not/exist\r\nI0922 00:05:37.069350  6372 dispatcher.cpp:149] Thread: 6372 requesting a stop\r\nI0922 00:05:37.069350  6372 dispatcher.cpp:122] Thread: 6372 requesting a join\r\nI0922 00:05:37.069350  6372 dispatcher.cpp:144] Services and threads have been cleared\r\n'
2020-09-22T00:05:37.2799743Z 77: ok
2020-09-22T00:05:42.5646981Z 77: test_config_check_failure_missing_plugin (__main__.OsqueryiTest) ... FAIL
2020-09-22T00:05:43.0585650Z 77: test_config_check_failure_valid_path (__main__.OsqueryiTest) ... ok
2020-09-22T00:05:43.0587028Z 77: test_config_check_success (__main__.OsqueryiTest)
2020-09-22T00:05:43.5936571Z 77: Test that a 0-config passes ... b''
2020-09-22T00:05:43.5939806Z 77: b'I0922 00:05:43.095897  5828 init.cpp:338] osquery initialized [version=4.5.0-11-gd75e6cda]\r\nI0922 00:05:43.096226  5828 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: \r\nI0922 00:05:43.096226  5828 rocksdb.cpp:132] Opening RocksDB handle: C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\osquery-tests-python-VssAdministrator\\tests.db4813\r\nI0922 00:05:43.348743  5828 init.cpp:549] An error occured during extension manager startup: Extensions disabled\r\nI0922 00:05:43.348743  5828 auto_constructed_tables.cpp:97] Removing stale ATC entries\r\nI0922 00:05:43.379779  5828 auto_constructed_tables.cpp:228] ATC table: test_atc Registered\r\nI0922 00:05:43.384800  5828 dispatcher.cpp:149] Thread: 5828 requesting a stop\r\nI0922 00:05:43.384800  5828 dispatcher.cpp:122] Thread: 5828 requesting a join\r\nI0922 00:05:43.384800  5828 dispatcher.cpp:144] Services and threads have been cleared\r\n'
2020-09-22T00:05:43.5943313Z 77: ok
2020-09-22T00:05:43.5943965Z 77: test_config_dump (__main__.OsqueryiTest)
2020-09-22T00:05:43.6401577Z 77: Test that config raw output is dumped when requested ... b'I0922 00:05:43.631747  1536 init.cpp:338] osquery initialized [version=4.5.0-11-gd75e6cda]\r\nI0922 00:05:43.632748  1536 extensions.cpp:453] Could not autoload extensions: Cannot open file for reading: \r\nI0922 00:05:43.632748  1536 init.cpp:549] An error occured during extension manager startup: Extensions disabled\r\nI0922 00:05:43.632748  1536 auto_constructed_tables.cpp:97] Removing stale ATC entries\r\nI0922 00:05:43.632748  1536 config.cpp:504] Requesting shutdown after dumping config\r\nI0922 00:05:43.633759  1536 dispatcher.cpp:149] Thread: 1536 requesting a stop\r\nI0922 00:05:43.633759  1536 dispatcher.cpp:122] Thread: 1536 requesting a join\r\nI0922 00:05:43.633759  1536 dispatcher.cpp:144] Services and threads have been cleared\r\n'
2020-09-22T00:05:43.6405065Z 77: ok
2020-09-22T00:05:43.6405815Z 77: test_error (__main__.OsqueryiTest)
2020-09-22T00:05:43.6406735Z 77: Test that we throw an error on bad query ... skipped 'stderr tests not supported on Windows.'
2020-09-22T00:05:43.6541418Z 77: test_foreign_tables (__main__.OsqueryiTest) ...   File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\unittest\case.py", line 120, in skip_wrapper
2020-09-22T00:05:43.6648923Z 77:     raise SkipTest(reason)
2020-09-22T00:05:43.6738784Z 77: 
2020-09-22T00:05:43.6766534Z 77:   File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\unittest\case.py", line 120, in skip_wrapper
2020-09-22T00:05:43.6823206Z 77:     raise SkipTest(reason)
2020-09-22T00:05:43.6869630Z 77: 
2020-09-22T00:05:43.6974259Z 77:   File "C:\hostedtoolcache\windows\Python\3.8.5\x64\lib\unittest\case.py", line 120, in skip_wrapper
2020-09-22T00:05:43.7072615Z 77:     raise SkipTest(reason)
2020-09-22T00:05:43.7122828Z 77: 
2020-09-22T00:05:43.7155872Z 77: Test (attempt 1) OsqueryiTest::test_foreign_tables failed: foreign table tests not supported on Windows.
2020-09-22T00:05:43.7194052Z 77: Test (attempt 2) OsqueryiTest::test_foreign_tables failed: foreign table tests not supported on Windows.
2020-09-22T00:05:43.7334834Z 77: Test (attempt 3) OsqueryiTest::test_foreign_tables failed: foreign table tests not supported on Windows.
2020-09-22T00:05:43.7385795Z 77: skipped 'foreign table tests not supported on Windows.'
2020-09-22T00:05:43.7391576Z 77: test_json_output (__main__.OsqueryiTest)
2020-09-22T00:05:43.7821802Z 77: Test that the output of --json is valid json ... b'[\r\n  {"0":"0"}\r\n]\r\n'
2020-09-22T00:05:43.7822858Z 77: b''
2020-09-22T00:05:43.7824006Z 77: ok
2020-09-22T00:05:43.7824699Z 77: test_meta_commands (__main__.OsqueryiTest)
2020-09-22T00:06:44.8125500Z 77: Test the supported meta shell/help/info commands ... ok
2020-09-22T00:06:45.8177829Z 77: test_time (__main__.OsqueryiTest) ... ok
2020-09-22T00:06:46.8230137Z 77: test_time_using_all (__main__.OsqueryiTest) ... ok
2020-09-22T00:06:46.8231561Z 77: 
2020-09-22T00:06:46.8233887Z 77: ======================================================================
2020-09-22T00:06:46.8234739Z 77: FAIL: test_config_check_failure_missing_plugin (__main__.OsqueryiTest)
2020-09-22T00:06:46.8235677Z 77: ----------------------------------------------------------------------
2020-09-22T00:06:46.8236401Z 77: Traceback (most recent call last):
2020-09-22T00:06:46.8237777Z 77:   File "test_osqueryi.py", line 126, in test_config_check_failure_missing_plugin
2020-09-22T00:06:46.8238536Z 77:     self.assertEqual(proc.proc.poll(), EXIT_CATASTROPHIC)
2020-09-22T00:06:46.8239202Z 77: AssertionError: 1 != 78
2020-09-22T00:06:46.8239954Z 77: 
2020-09-22T00:06:46.8240577Z 77: ----------------------------------------------------------------------
2020-09-22T00:06:46.8241266Z 77: Ran 14 tests in 73.414s
2020-09-22T00:06:46.8241812Z 77: 
2020-09-22T00:06:46.8242394Z 77: FAILED (failures=1, skipped=2)
2020-09-22T00:06:46.8560865Z 77/78 Test #77: tools_tests_testosqueryi ......................................***Failed   73.64 sec
```

**Comment by theopolis** [comment]
I think this is fixed. Please keep a look out if the test fails again since landing #6688.
